name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Build Main Branch
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Otorgar permisos de ejecución al script .sh
        run: chmod +x ./version.sh

      - name: Versioning
        id: version
        run: echo "new_version=$(./version.sh)" >> $GITHUB_OUTPUT

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Rename Jar
        run: mv ./target/AuthRmi-1.0-SNAPSHOT.jar ./target/AuthRmi-${{ steps.version.outputs.new_version }}.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          files: |
            ./target/AuthRmi-${{ steps.version.outputs.new_version }}.jar

  merge:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge test -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: test
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build Main Branch
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.new_version }}
          files: |
            ./target/AuthRmi-${{ steps.version.outputs.new_version }}.jar
