name: CI Build

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn -B package --file pom.xml
      
      - name: Run test
        run: echo "Testing..."

      - name: Upload jar
        uses: actions/upload-artifact@master
        with:
          name: app-jar
          path: ./target/AuthRmi-1.0-SNAPSHOT.jar

  version:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grants permisions
        run: chmod +x ./version.sh

      - name: Change version
        id: version
        run: echo "new_version=$(./version.sh "${{ github.event.head_commit.message }}")" >> $GITHUB_OUTPUT

      - name: Update version file
        run: |
          git config --global user.name 'diegomated1'
          git config --global user.email 'diegocardwr@gmail.com'
          git add ./version
          git commit -am "chore: version ${{ steps.version.outputs.new_version }}"
          git push

      - name: Merge to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [version]
    if: success()
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download jar
        uses: actions/download-artifact@master
        with:
          name: app-jar
          path: .

      - name: Rename Jar
        run: mv ./AuthRmi-1.0-SNAPSHOT.jar ./AuthRmi-${{ needs.check.outputs.new_version }}.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check.outputs.new_version }}
          files: |
            ./AuthRmi-${{ needs.check.outputs.new_version }}.jar