name: CI Build

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      new_version: ${{ steps.step1.outputs.new_version }}
    steps:
      - id: step1
        run: echo "new_version=v1.0.1" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.new_version}}
        run: echo "$OUTPUT1 $OUTPUT2"