name: CI Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crer
        run: |
          echo "holas" >> pepe.txt
          git config --global user.name 'diegomated1'
          git config --global user.email 'diegocardwr@gmail.com'
          git commit -am "chore: version"
          git push

      - name: Merge test -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}