name: CI Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crer
        run: |
          echo "holas" >> pepe.txt
          git add ./pepe.txt

      - name: Merge test -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: 'chore: version'
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}